using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ContextCore.Generators;

/// <summary>
/// 源生成器：根据 <see cref="GenerateInvalidatingDecoratorAttribute"/> 生成失效装饰器的基础结构。
/// 生成：_inner 字段、构造函数（调用 base(invalidator, versionStore)）、只读方法（透传到 _inner）。
/// 写入方法（非 Get/Query/List/Search 开头）由手写 partial 类提供，调用 AfterCommitAsync 触发失效。
/// </summary>
[Generator]
public sealed class InvalidatingDecoratorGenerator : IIncrementalGenerator
{
    private const string AttributeFullyQualifiedName = "ContextCore.Core.GenerateInvalidatingDecoratorAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullyQualifiedName,
            predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
            transform: static (ctx, ct) =>
            {
                var classSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
                var attrData = ctx.Attributes[0];

                var interfaceType = attrData.ConstructorArguments[0].Value as INamedTypeSymbol;

                ct.ThrowIfCancellationRequested();

                return new DecoratorSpec(
                    classSymbol.ContainingNamespace.ToDisplayString(),
                    classSymbol.Name,
                    interfaceType!);
            });

        context.RegisterSourceOutput(provider, static (spc, spec) =>
        {
            var source = GenerateSource(spec);
            spc.AddSource($"{spec.ClassName}_Decorator.g.cs", source);
        });
    }

    private static string GenerateSource(DecoratorSpec spec)
    {
        var interfaceName = spec.InterfaceType.ToDisplayString(CodeGenerationHelpers.TypeFormat);
        var interfaceShortName = spec.InterfaceType.Name;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>由 ContextCore.Generators.InvalidatingDecoratorGenerator 生成。请勿手动编辑。</auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {spec.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// 失效边界 Decorator 基础结构（自动生成）：包装 <see cref=\"{interfaceName}\"/>，");
        sb.AppendLine("/// 在写入成功后触发缓存失效。只读方法透传到 _inner；写入方法在手写 partial 中实现。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed partial class {spec.ClassName} : InvalidatingStoreDecoratorBase, {interfaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {interfaceName} _inner;");
        sb.AppendLine();
        sb.AppendLine($"    public {spec.ClassName}(");
        sb.AppendLine($"        {interfaceName} inner,");
        sb.AppendLine("        ContextCore.Abstractions.IStateCacheInvalidator invalidator,");
        sb.AppendLine("        ContextCore.Abstractions.IContextStateVersionStore? versionStore = null)");
        sb.AppendLine("        : base(invalidator, versionStore)");
        sb.AppendLine("    {");
        sb.AppendLine("        _inner = inner;");
        sb.AppendLine("    }");
        sb.AppendLine();

        int readMethodCount = 0;
        foreach (var method in CodeGenerationHelpers.EnumerateInterfaceMethods(spec.InterfaceType))
        {
            if (!CodeGenerationHelpers.IsReadMethod(method))
            {
                continue;
            }

            var signature = CodeGenerationHelpers.FormatMethodSignature(method);
            var callArgs = CodeGenerationHelpers.FormatCallArguments(method.Parameters);
            var genericSuffix = method.IsGenericMethod
                ? $"<{string.Join(", ", method.TypeParameters.Select(t => t.Name))}>"
                : "";

            sb.AppendLine($"    public {signature}");
            sb.AppendLine($"        => _inner.{method.Name}{genericSuffix}({callArgs});");
            sb.AppendLine();

            readMethodCount++;
        }

        if (readMethodCount == 0)
        {
            sb.AppendLine("    // 此接口无只读方法，所有方法均为写入方法，需在手写 partial 中实现。");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private sealed class DecoratorSpec
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public INamedTypeSymbol InterfaceType { get; }

        public DecoratorSpec(string ns, string className, INamedTypeSymbol interfaceType)
        {
            Namespace = ns;
            ClassName = className;
            InterfaceType = interfaceType;
        }
    }
}
