using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ContextCore.Generators;

/// <summary>
/// 源生成器：根据 <see cref="GenerateUnsupportedStoreAttribute"/> 生成完整的 Unsupported 存储实现。
/// 所有方法抛出 NotSupportedException，构造函数接收 provider 名称字符串。
/// </summary>
[Generator]
public sealed class UnsupportedStoreGenerator : IIncrementalGenerator
{
    private const string AttributeFullyQualifiedName = "ContextCore.Core.GenerateUnsupportedStoreAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullyQualifiedName,
            predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
            transform: static (ctx, ct) =>
            {
                var classSymbol = (INamedTypeSymbol)ctx.TargetSymbol;
                var attrData = ctx.Attributes[0];

                var interfaceType = attrData.ConstructorArguments[0].Value as INamedTypeSymbol;
                var displayName = attrData.ConstructorArguments[1].Value as string ?? "store";

                ct.ThrowIfCancellationRequested();

                return new UnsupportedStoreSpec(
                    classSymbol.ContainingNamespace.ToDisplayString(),
                    classSymbol.Name,
                    interfaceType!,
                    displayName!);
            });

        context.RegisterSourceOutput(provider, static (spc, spec) =>
        {
            var source = GenerateSource(spec);
            spc.AddSource($"{spec.ClassName}_Unsupported.g.cs", source);
        });
    }

    private static string GenerateSource(UnsupportedStoreSpec spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>由 ContextCore.Generators.UnsupportedStoreGenerator 生成。请勿手动编辑。</auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {spec.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>未实现持久化后端时的显式占位存储。所有方法抛出 NotSupportedException。</summary>");
        sb.AppendLine($"public sealed partial class {spec.ClassName} : {spec.InterfaceType.ToDisplayString(CodeGenerationHelpers.TypeFormat)}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly string _provider;");
        sb.AppendLine();
        sb.AppendLine($"    public {spec.ClassName}(string provider)");
        sb.AppendLine("    {");
        sb.AppendLine("        _provider = string.IsNullOrWhiteSpace(provider) ? \"unknown\" : provider;");
        sb.AppendLine("    }");
        sb.AppendLine();

        var displayNameLower = char.ToLowerInvariant(spec.DisplayName[0]) + spec.DisplayName.Substring(1);

        foreach (var method in CodeGenerationHelpers.EnumerateInterfaceMethods(spec.InterfaceType))
        {
            var signature = CodeGenerationHelpers.FormatMethodSignature(method);
            var args = CodeGenerationHelpers.FormatCallArguments(method.Parameters);

            // 对于泛型方法，约束需要从接口复制
            var constraints = FormatTypeParameterConstraints(method);

            sb.AppendLine($"    public {signature}{constraints}");
            sb.AppendLine("    {");
            sb.AppendLine($"        throw CreateException();");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("    private System.NotSupportedException CreateException()");
        sb.AppendLine($"        => new($\"{displayNameLower} is not implemented for storage provider '{{_provider}}'.\");");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string FormatTypeParameterConstraints(IMethodSymbol method)
    {
        if (!method.IsGenericMethod)
        {
            return string.Empty;
        }

        var sb = new StringBuilder();
        foreach (var tp in method.TypeParameters)
        {
            if (tp.HasValueTypeConstraint)
            {
                sb.AppendLine();
                sb.Append($"    where {tp.Name} : struct");
            }
            if (tp.HasReferenceTypeConstraint)
            {
                sb.AppendLine();
                sb.Append($"    where {tp.Name} : class");
            }
            if (tp.HasNotNullConstraint)
            {
                sb.AppendLine();
                sb.Append($"    where {tp.Name} : notnull");
            }
            foreach (var constraintType in tp.ConstraintTypes)
            {
                sb.AppendLine();
                sb.Append($"    where {tp.Name} : {constraintType.ToDisplayString(CodeGenerationHelpers.TypeFormat)}");
            }
            if (tp.HasConstructorConstraint)
            {
                sb.AppendLine();
                sb.Append($"    where {tp.Name} : new()");
            }
        }

        return sb.Length > 0 ? sb.ToString() : string.Empty;
    }

    private sealed class UnsupportedStoreSpec
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public INamedTypeSymbol InterfaceType { get; }
        public string DisplayName { get; }

        public UnsupportedStoreSpec(string ns, string className, INamedTypeSymbol interfaceType, string displayName)
        {
            Namespace = ns;
            ClassName = className;
            InterfaceType = interfaceType;
            DisplayName = displayName;
        }
    }
}
