using System.Text.Json;

namespace ContextCore.Tests;

[TestClass]
[TestCategory("Synthetic")]
[TestCategory("Gate")]
public class ContextCoreNativeProductionTraceEndpointApprovalValidatorTests
{
    private static string Resolve(string f) => TestRepoFileResolver.Resolve("learning", "v16_23", f);

    [TestMethod]
    public void Plan_Ready_ButNotImplemented()
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(Resolve("native-production-trace-endpoint-approval-validator-implementation-plan.json")));
        var ps = doc.RootElement.GetProperty("PlanStatus");
        Assert.IsTrue(ps.GetProperty("ApprovalValidatorImplementationPlanReady").GetBoolean());
        Assert.IsFalse(ps.GetProperty("ApprovalValidatorImplemented").GetBoolean());
        Assert.IsFalse(ps.GetProperty("GoDecision").GetBoolean());
    }

    [TestMethod]
    public void Contract_ArtifactExists_False_ValidationNotAttempted()
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(Resolve("native-production-trace-endpoint-approval-validator-contract.json")));
        var o = doc.RootElement.GetProperty("Outputs");
        Assert.IsFalse(o.GetProperty("ArtifactExists").GetBoolean());
        Assert.IsFalse(o.GetProperty("ValidationAttempted").GetBoolean());
        Assert.IsFalse(o.GetProperty("ApprovalAccepted").GetBoolean());
        Assert.IsFalse(o.GetProperty("GoCandidateAllowed").GetBoolean());
    }

    [TestMethod]
    public void StateMachine_CurrentState_NoArtifactToReview()
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(Resolve("native-production-trace-endpoint-approval-validator-state-machine.json")));
        Assert.AreEqual("NoArtifactToReview", doc.RootElement.GetProperty("CurrentState").GetString());
        var forbidden = doc.RootElement.GetProperty("ForbiddenTransitions");
        Assert.IsTrue(forbidden.GetArrayLength() >= 3);
    }

    [TestMethod]
    public void RejectionMapping_FifteenMappings_OnlyMissingArtifactTriggered()
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(Resolve("native-production-trace-endpoint-approval-validator-rejection-mapping.json")));
        var maps = doc.RootElement.GetProperty("Mappings");
        Assert.AreEqual(15, maps.GetArrayLength());
        int triggered = 0;
        foreach (var m in maps.EnumerateArray())
            if (m.GetProperty("Triggered").GetBoolean()) triggered++;
        Assert.AreEqual(1, triggered);
    }

    [TestMethod]
    public void AuditLogSchema_ExcludesApprovalTokenPlaintext()
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(Resolve("native-production-trace-endpoint-approval-validator-audit-log-schema.json")));
        var excluded = doc.RootElement.GetProperty("ExcludedFromLog");
        Assert.IsTrue(excluded.GetArrayLength() >= 3);
    }

    [TestMethod]
    public void TestMatrix_SeventeenScenarios_MostlyNoGo()
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(Resolve("native-production-trace-endpoint-approval-validator-test-matrix.json")));
        var scenarios = doc.RootElement.GetProperty("Scenarios");
        Assert.IsTrue(scenarios.GetArrayLength() >= 16);
        int goCount = 0;
        foreach (var s in scenarios.EnumerateArray())
            if (s.GetProperty("GoDecision").GetBoolean()) goCount++;
        Assert.AreEqual(1, goCount);
    }

    [TestMethod]
    public void V16_23Gate_AllFlagsCorrect()
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(Resolve("native-production-trace-endpoint-approval-validator-v16-23-gate.json")));
        var gr = doc.RootElement.GetProperty("GateResult");
        Assert.IsTrue(gr.GetProperty("GatePassed").GetBoolean());
        Assert.IsFalse(gr.GetProperty("ApprovalValidatorImplemented").GetBoolean());
        Assert.AreEqual("NoArtifactToReview", gr.GetProperty("CurrentValidatorState").GetString());
    }

    [TestMethod]
    public void NoJsonl()
    {
        // Use checked-in plan file to resolve learning dir (not generator output)
        var planPath = Resolve("native-production-trace-endpoint-approval-validator-implementation-plan.json");
        var learningDir = System.IO.Path.GetDirectoryName(System.IO.Path.GetDirectoryName(planPath)!)!;
        foreach (var d in new[] { "v16_14", "v16_15", "v16_16", "v16_17", "v16_18", "v16_19", "v16_20", "v16_21", "v16_22", "v16_23" })
            if (Directory.Exists(System.IO.Path.Combine(learningDir, d)))
                Assert.AreEqual(0, Directory.GetFiles(System.IO.Path.Combine(learningDir, d), "*.jsonl").Length, $"{d}: jsonl must be 0.");
    }

    [TestMethod]
    public void CheckedInArtifacts_HaveParityFields_BeforeGeneratorRuns()
    {
        // Read checked-in files (plan is not generated by this test, so resolver finds repo root)
        var planPath = Resolve("native-production-trace-endpoint-approval-validator-implementation-plan.json");
        var vDir = System.IO.Path.GetDirectoryName(planPath)!;
        var gatePath = System.IO.Path.Combine(vDir, "native-production-trace-endpoint-approval-validator-v16-23-gate.json");
        var pePath = System.IO.Path.Combine(vDir, "native-production-trace-endpoint-approval-validator-generator-parity-evidence.json");

        using var gate = JsonDocument.Parse(File.ReadAllText(gatePath));
        var gr = gate.RootElement.GetProperty("GateResult");
        Assert.IsTrue(gr.TryGetProperty("ApprovalValidatorGeneratorParityEvidenceReady", out _));
        Assert.IsTrue(gr.TryGetProperty("ApprovalValidatorGeneratorParityPassed", out _));
        Assert.IsTrue(gate.RootElement.GetProperty("PreviousGatesPreserved").TryGetProperty("V16_23GeneratorParityReady", out _));

        using var pe = JsonDocument.Parse(File.ReadAllText(pePath));
        var cr0 = pe.RootElement.GetProperty("ComparisonResults")[0];
        Assert.IsTrue(cr0.TryGetProperty("CheckedInPropertyCount", out _));
        Assert.IsTrue(cr0.TryGetProperty("GeneratedPropertyCount", out _));
        Assert.IsTrue(cr0.TryGetProperty("ExtraPropertyPaths", out _));
        Assert.IsTrue(cr0.TryGetProperty("TypeMismatchPaths", out _));
        Assert.IsTrue(pe.RootElement.GetProperty("ParitySummary").TryGetProperty("TotalPropertiesChecked", out _));
    }

    [TestMethod]
    public void GeneratorParity_RunGeneratorAndCheckKeyFields()
    {
        var assembly = typeof(ContextCore.Evaluation.Commands.EvalCommand).Assembly;
        var type = assembly.GetType("ContextCore.Evaluation.Commands.EvalCommand")!;
        var method = type.GetMethod("ExecuteV16_23NativeProductionTraceEndpointApprovalValidatorPlanAsync",
            System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)!;
        var task = method.Invoke(null, [Array.Empty<string>(), CancellationToken.None]) as Task;
        Assert.IsNotNull(task);
        task!.GetAwaiter().GetResult();

        // Contract: check Type, ValidationNeverAttempted, CurrentExpectedBehavior
        using var doc = JsonDocument.Parse(File.ReadAllText(Resolve("native-production-trace-endpoint-approval-validator-contract.json")));
        Assert.IsTrue(doc.RootElement.GetProperty("ContractStatus").TryGetProperty("ValidationNeverAttempted", out _));
        Assert.IsTrue(doc.RootElement.GetProperty("Inputs")[0].TryGetProperty("Type", out _));
        Assert.IsTrue(doc.RootElement.TryGetProperty("CurrentExpectedBehavior", out _));

        // State machine: States are objects, transitions have Trigger/Reason
        using var sm = JsonDocument.Parse(File.ReadAllText(Resolve("native-production-trace-endpoint-approval-validator-state-machine.json")));
        Assert.IsTrue(sm.RootElement.GetProperty("States")[0].TryGetProperty("Description", out _));
        Assert.IsTrue(sm.RootElement.GetProperty("ValidTransitions")[0].TryGetProperty("Trigger", out _));
        Assert.IsTrue(sm.RootElement.GetProperty("ForbiddenTransitions")[0].TryGetProperty("Reason", out _));

        // Rejection: SourceRule, UserFacingMessage, AuditField, MappingSummary
        using var rj = JsonDocument.Parse(File.ReadAllText(Resolve("native-production-trace-endpoint-approval-validator-rejection-mapping.json")));
        var m0 = rj.RootElement.GetProperty("Mappings")[0];
        Assert.IsTrue(m0.TryGetProperty("SourceRule", out _));
        Assert.IsTrue(m0.TryGetProperty("UserFacingMessage", out _));
        Assert.IsTrue(m0.TryGetProperty("AuditField", out _));
        Assert.IsTrue(rj.RootElement.TryGetProperty("MappingSummary", out _));

        // Audit: AuditLogFields objects with Type/RequiredForAllRuns, CurrentLogState
        using var al = JsonDocument.Parse(File.ReadAllText(Resolve("native-production-trace-endpoint-approval-validator-audit-log-schema.json")));
        var al0 = al.RootElement.GetProperty("AuditLogFields")[0];
        Assert.IsTrue(al0.TryGetProperty("Type", out _));
        Assert.IsTrue(al0.TryGetProperty("RequiredForAllRuns", out _));
        Assert.IsTrue(al.RootElement.TryGetProperty("CurrentLogState", out _));

        // Test matrix: ApprovalArtifactExists, InputArtifact, ExpectedOutcome, Summary
        using var tm = JsonDocument.Parse(File.ReadAllText(Resolve("native-production-trace-endpoint-approval-validator-test-matrix.json")));
        var s0 = tm.RootElement.GetProperty("Scenarios")[0];
        Assert.IsTrue(s0.TryGetProperty("ApprovalArtifactExists", out _));
        Assert.IsTrue(s0.TryGetProperty("InputArtifact", out _));
        Assert.IsTrue(s0.TryGetProperty("ExpectedOutcome", out _));
        Assert.IsTrue(tm.RootElement.TryGetProperty("Summary", out _));

        // Gate: parity fields present after generator runs
        using var gate = JsonDocument.Parse(File.ReadAllText(Resolve("native-production-trace-endpoint-approval-validator-v16-23-gate.json")));
        var gr = gate.RootElement.GetProperty("GateResult");
        Assert.IsTrue(gr.TryGetProperty("ApprovalValidatorGeneratorParityEvidenceReady", out _));
        Assert.IsTrue(gr.TryGetProperty("ApprovalValidatorGeneratorParityPassed", out _));

        // Parity evidence: check full fields after generator runs
        using var pe = JsonDocument.Parse(File.ReadAllText(Resolve("native-production-trace-endpoint-approval-validator-generator-parity-evidence.json")));
        var cr0 = pe.RootElement.GetProperty("ComparisonResults")[0];
        Assert.IsTrue(cr0.TryGetProperty("CheckedInPropertyCount", out _));
        Assert.IsTrue(cr0.TryGetProperty("GeneratedPropertyCount", out _));
        Assert.IsTrue(cr0.TryGetProperty("ExtraPropertyPaths", out _));
        Assert.IsTrue(cr0.TryGetProperty("TypeMismatchPaths", out _));
    }
}
